//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProductsOrders
    {
        public double Id { get; set; }
        public Nullable<double> IdProduct { get; set; }
        public Nullable<double> IdPartner { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
