//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.PartnerProductsOrders = new HashSet<PartnerProductsOrders>();
        }
    
        public double Id { get; set; }
        public Nullable<double> IdTypeMaterial { get; set; }
        public string Name { get; set; }
        public Nullable<double> Articul { get; set; }
        public Nullable<double> MinPrice { get; set; }
        public string ImagePath { get; set; }
        public string Description { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProductsOrders> PartnerProductsOrders { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
